version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Training phase started
      - aws --version
  build:
    commands:
      - python ml_pipeline.py
  post_build:
    commands:
      - echo Build completed
      - ls -la
artifacts:
  files:
    - '**/*'
  name: TrainingOutput
