version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - |
        if [ "$CODEBUILD_INITIATOR" = "codepipeline/DeployToStaging" ]; then
          python deploy_model.py
        else
          python ml_pipeline.py
        fi
artifacts:
  files:
    - '**/*'
