AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Validated MLOps CFN: CodeStar Connection -> CodePipeline -> CodeBuild (Train, Deploy) -> SageMaker Model Package Group
  Hardened S3, scoped IAM (for PoC), lifecycle, manual approval gate, and CodeBuild envs for DATA_S3_URI.

# NOTE: The CodeStar connection ARN (CodeConnectionArn) must be created in the SAME AWS region
# where you deploy this stack. If you deploy to a different region than the connection, the
# pipeline source stage will fail.

Parameters:
  GitHubOwner:
    Type: String
    Description: GitHub repository owner/organization
    Default: debarshi24
  GitHubRepo:
    Type: String
    Description: GitHub repository name
    Default: mlops-poc
  GitHubBranch:
    Type: String
    Default: main
    Description: GitHub branch to track
  CodeConnectionArn:
    Type: String
    Description: ARN of the CodeStar Connection to GitHub (must exist in the same region as this stack)
    Default: arn:aws:codeconnections:eu-west-1:361509912577:connection/3600e1d6-0460-4922-938c-3e7c5ad02a74
  ModelPackageGroupName:
    Type: String
    Default: mlops-poc-model-group-dsa
    Description: SageMaker Model Package Group name
  AutoApproveModels:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: Automatically approve models that meet criteria

Mappings:
  RegionToImage:
    default:
      CodeBuildImage: aws/codebuild/standard:7.0

Resources:

  ####################################################
  # S3 Bucket for artifacts (hardened & lifecycle)
  ####################################################
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldArtifacts
            Status: Enabled
            ExpirationInDays: 30
      Tags:
        - Key: Project
          Value: MLOps-PoC

  ####################################################
  # IAM Roles (no explicit RoleName; CloudFormation will generate unique names)
  ####################################################

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:GetBucketLocation
                  - s3:ListBucket
                Resource:
                  - !GetAtt ArtifactsBucket.Arn
                  - !Join ['', [ !GetAtt ArtifactsBucket.Arn, '/*' ]]
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource:
                  - !GetAtt CodeBuildProject.Arn
                  - !GetAtt CodeBuildDeployProject.Arn
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource: !Ref CodeConnectionArn
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !GetAtt CodeBuildTrainRole.Arn
                  - !GetAtt CodeBuildDeployRole.Arn
                  - !GetAtt SageMakerExecutionRole.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  CodeBuildTrainRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: CodeBuildTrainInline
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt ArtifactsBucket.Arn
                  - !Join ['', [ !GetAtt ArtifactsBucket.Arn, '/*' ]]
              - Effect: Allow
                Action:
                  - sagemaker:CreateTrainingJob
                  - sagemaker:DescribeTrainingJob
                  - sagemaker:CreateModel
                Resource: !Sub 'arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:*'
              - Effect: Allow
                Action:
                  - sagemaker:CreateModelPackage
                  - sagemaker:DescribeModelPackage
                  - sagemaker:ListModelPackages
                  - sagemaker:UpdateModelPackage
                Resource: !Sub 'arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:model-package-group/${ModelPackageGroupName}/*'
              - Effect: Allow
                Action:
                  - sagemaker:CreateModelPackageGroup
                  - sagemaker:DescribeModelPackageGroup
                  - sagemaker:ListModelPackageGroups
                Resource: !Sub 'arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:model-package-group/${ModelPackageGroupName}'
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !GetAtt SageMakerExecutionRole.Arn

  CodeBuildDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: CodeBuildDeployInline
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt ArtifactsBucket.Arn
                  - !Join ['', [ !GetAtt ArtifactsBucket.Arn, '/*' ]]
              - Effect: Allow
                Action:
                  - sagemaker:CreateEndpointConfig
                  - sagemaker:CreateEndpoint
                  - sagemaker:UpdateEndpoint
                  - sagemaker:DescribeEndpoint
                  - sagemaker:InvokeEndpoint
                Resource: !Sub 'arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:*'
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !GetAtt SageMakerExecutionRole.Arn

  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Policies:
        - PolicyName: SageMakerS3Inline
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt ArtifactsBucket.Arn
                  - !Join ['', [ !GetAtt ArtifactsBucket.Arn, '/*' ]]

  ####################################################
  # SageMaker Model Package Group
  ####################################################
  ModelPackageGroup:
    Type: AWS::SageMaker::ModelPackageGroup
    Properties:
      ModelPackageGroupName: !Ref ModelPackageGroupName
      ModelPackageGroupDescription: 'Model package group for demo ML models'
      Tags:
        - Key: Project
          Value: MLOps-Demo
        - Key: Environment
          Value: Development
        - Key: Owner
          Value: MLOps-Team
        - Key: Purpose
          Value: Automated-ML-Pipeline

  ####################################################
  # CodeBuild Projects
  ####################################################

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${AWS::StackName}-ml-train'
      ServiceRole: !GetAtt CodeBuildTrainRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: !FindInMap [RegionToImage, default, CodeBuildImage]
        EnvironmentVariables:
          - Name: SAGEMAKER_ROLE_ARN
            Value: !GetAtt SageMakerExecutionRole.Arn
          - Name: S3_BUCKET
            Value: !Ref ArtifactsBucket
          - Name: DATA_S3_URI
            Value: !Sub 's3://${ArtifactsBucket}/data/raw/Topic_15_poc_customers.csv'
          - Name: MODEL_PACKAGE_GROUP_NAME
            Value: !Ref ModelPackageGroupName
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: AUTO_APPROVE_MODELS
            Value: !Ref AutoApproveModels
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                python: 3.9
              commands:
                - pip install --upgrade pip
                - pip install -r requirements.txt
            pre_build:
              commands:
                - echo "Training phase started on `date`"
                - aws --version
                - echo "S3_BUCKET=$S3_BUCKET"
                - echo "DATA_S3_URI=$DATA_S3_URI"
                - echo "MODEL_PACKAGE_GROUP_NAME=$MODEL_PACKAGE_GROUP_NAME"
            build:
              commands:
                - echo "Build started on `date`"
                - python ml_pipeline.py
            post_build:
              commands:
                - echo "Build completed on `date`"
                - echo "Artifacts produced:"
                - ls -la
          artifacts:
            files:
              - '**/*'
            name: TrainingOutput

  CodeBuildDeployProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${AWS::StackName}-ml-deploy'
      ServiceRole: !GetAtt CodeBuildDeployRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !FindInMap [RegionToImage, default, CodeBuildImage]
        EnvironmentVariables:
          - Name: SAGEMAKER_ROLE_ARN
            Value: !GetAtt SageMakerExecutionRole.Arn
          - Name: S3_BUCKET
            Value: !Ref ArtifactsBucket
          - Name: DATA_S3_URI
            Value: !Sub 's3://${ArtifactsBucket}/data/raw/Topic_15_poc_customers.csv'
          - Name: MODEL_PACKAGE_GROUP_NAME
            Value: !Ref ModelPackageGroupName
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          phases:
            install:
              runtime-versions:
                python: 3.9
              commands:
                - pip install --upgrade pip
                - pip install boto3 sagemaker
            build:
              commands:
                - python deploy_model.py

  ####################################################
  # CodePipeline definition
  ####################################################
  MLOpsPipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn:
      - CodeBuildProject
      - CodeBuildDeployProject
      - CodePipelineRole
    Properties:
      Name: !Sub '${AWS::StackName}-mlops-pipeline'
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactsBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref CodeConnectionArn
                FullRepositoryId: !Sub '${GitHubOwner}/${GitHubRepo}'
                BranchName: !Ref GitHubBranch
                OutputArtifactFormat: CODE_ZIP
              OutputArtifacts:
                - Name: SourceOutput
              RunOrder: 1

        - Name: TrainAndEvaluate
          Actions:
            - Name: TrainModel
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref CodeBuildProject
                PrimarySource: SourceOutput
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: TrainingOutput
              RunOrder: 1

        - Name: ApprovalGate
          Actions:
            - Name: ManualApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                CustomData: 'Please review generated metrics (in artifacts) and approve to deploy'
              RunOrder: 1

        - Name: DeployToStaging
          Actions:
            - Name: DeployModel
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref CodeBuildDeployProject
                PrimarySource: SourceOutput
              InputArtifacts:
                - Name: SourceOutput
                - Name: TrainingOutput
              RunOrder: 1

Outputs:
  PipelineName:
    Description: Name of the CodePipeline
    Value: !Ref MLOpsPipeline

  PipelineUrl:
    Description: URL of the CodePipeline
    Value: !Sub 'https://console.aws.amazon.com/codesuite/codepipeline/pipelines/${MLOpsPipeline}/view?region=${AWS::Region}'

  ArtifactsBucket:
    Description: S3 bucket for pipeline artifacts (bucket name)
    Value: !Ref ArtifactsBucket

  SampleCSVS3URI:
    Description: S3 URI where the sample CSV should be placed for pipeline runs
    Value: !Sub 's3://${ArtifactsBucket}/data/raw/Topic_15_poc_customers.csv'

  SageMakerRole:
    Description: SageMaker execution role ARN
    Value: !GetAtt SageMakerExecutionRole.Arn

  ModelPackageGroup:
    Description: SageMaker Model Package Group name
    Value: !Ref ModelPackageGroupName